(function () {
  "use strict";

  const CHAT_ENDPOINT = "/api/chat";
  const MODEL = "claude-sonnet-4-5-20250929";

  const els = {
    setup: document.getElementById("setup"),
    startBtn: document.getElementById("start-btn"),
    configError: document.getElementById("config-error"),
    chatWrap: document.getElementById("chat-wrap"),
    composer: document.getElementById("composer"),
    input: document.getElementById("input"),
    sendBtn: document.getElementById("send-btn"),
    resultBar: document.getElementById("result-bar"),
    dlCsv: document.getElementById("dl-csv"),
    dlJson: document.getElementById("dl-json"),
    dlMd: document.getElementById("dl-md"),
    resetBtn: document.getElementById("reset-btn"),
  };

  let messages = []; // {role, content}
  let latestRow = null; // parsed JSON object once finalized
  let sending = false;

  function saveSessionState() {
    try {
      sessionStorage.setItem("dm_messages", JSON.stringify(messages));
    } catch (e) {
      /* ignore storage errors (private browsing, etc.) */
    }
  }

  function restoreSessionState() {
    try {
      const msgs = sessionStorage.getItem("dm_messages");
      if (msgs) messages = JSON.parse(msgs);
    } catch (e) {
      /* ignore */
    }
  }

  function clearSession() {
    try {
      sessionStorage.removeItem("dm_messages");
    } catch (e) {
      /* ignore */
    }
    location.reload();
  }

  function addMessageToDom(role, text) {
    const wrap = document.createElement("div");
    wrap.className = "msg " + role;
    const bubble = document.createElement("div");
    bubble.className = "bubble";
    bubble.textContent = stripJsonBlock(text);
    wrap.appendChild(bubble);
    els.chatWrap.appendChild(wrap);
    els.chatWrap.scrollTop = els.chatWrap.scrollHeight;
    return bubble;
  }

  function addTypingIndicator() {
    const wrap = document.createElement("div");
    wrap.className = "msg assistant";
    wrap.id = "typing-indicator";
    const bubble = document.createElement("div");
    bubble.className = "bubble";
    bubble.innerHTML = '<span class="typing"><span></span><span></span><span></span></span>';
    wrap.appendChild(bubble);
    els.chatWrap.appendChild(wrap);
    els.chatWrap.scrollTop = els.chatWrap.scrollHeight;
  }

  function removeTypingIndicator() {
    const el = document.getElementById("typing-indicator");
    if (el) el.remove();
  }

  function showError(msg) {
    const box = document.createElement("div");
    box.className = "errbox";
    box.textContent = msg;
    els.chatWrap.appendChild(box);
    els.chatWrap.scrollTop = els.chatWrap.scrollHeight;
  }

  // Extract a fenced ```json ... ``` block from assistant text, if present.
  function extractJsonBlock(text) {
    const match = text.match(/```json\s*([\s\S]*?)```/i);
    if (!match) return null;
    try {
      return JSON.parse(match[1].trim());
    } catch (e) {
      return null;
    }
  }

  function stripJsonBlock(text) {
    return text.replace(/```json\s*[\s\S]*?```/i, "").trim() || text;
  }

  function csvEscape(val) {
    const s = val === undefined || val === null ? "" : String(val);
    if (/[",\n]/.test(s)) {
      return '"' + s.replace(/"/g, '""') + '"';
    }
    return s;
  }

  function downloadText(filename, content, mime) {
    const blob = new Blob([content], { type: mime || "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  function buildCsv(row) {
    const header = COLUMNS.map(csvEscape).join(",");
    const values = COLUMNS.map((c) => csvEscape(row[c])).join(",");
    return header + "\n" + values + "\n";
  }

  function buildMarkdown(row) {
    let out = "# Data Mapping Register — Draft Row\n\n";
    out += "_Generated by the Data Mapping Intake Assistant. Review before sending to Legal/Privacy._\n\n";
    for (const c of COLUMNS) {
      out += `**${c}:** ${row[c] && String(row[c]).trim() !== "" ? row[c] : "N/A"}\n\n`;
    }
    return out;
  }

  function showResultBar(row) {
    latestRow = row;
    els.resultBar.classList.add("visible");
  }

  els.dlCsv.addEventListener("click", () => {
    if (!latestRow) return;
    downloadText("data-mapping-row.csv", buildCsv(latestRow), "text/csv");
  });
  els.dlJson.addEventListener("click", () => {
    if (!latestRow) return;
    downloadText("data-mapping-row.json", JSON.stringify(latestRow, null, 2), "application/json");
  });
  els.dlMd.addEventListener("click", () => {
    if (!latestRow) return;
    downloadText("data-mapping-row.md", buildMarkdown(latestRow), "text/markdown");
  });

  // Calls our own backend (api/chat.js), which holds the Anthropic API key
  // server-side. The browser never sees or handles any API key.
  async function callAssistant(msgs) {
    const res = await fetch(CHAT_ENDPOINT, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        model: MODEL,
        system: SYSTEM_PROMPT,
        messages: msgs.map((m) => ({ role: m.role, content: m.content })),
      }),
    });

    let data;
    try {
      data = await res.json();
    } catch (e) {
      throw new Error(`Unexpected response from server (${res.status}).`);
    }

    if (!res.ok) {
      throw new Error(data.error || `Server error (${res.status}).`);
    }
    return data.text;
  }

  async function sendMessage(userText) {
    if (sending) return;
    sending = true;
    els.sendBtn.disabled = true;

    messages.push({ role: "user", content: userText });
    addMessageToDom("user", userText);
    saveSessionState();

    addTypingIndicator();
    try {
      const replyText = await callAssistant(messages);
      removeTypingIndicator();

      messages.push({ role: "assistant", content: replyText });
      addMessageToDom("assistant", replyText);
      saveSessionState();

      const row = extractJsonBlock(replyText);
      if (row) showResultBar(row);
    } catch (err) {
      removeTypingIndicator();
      showError(err.message || String(err));
    } finally {
      sending = false;
      els.sendBtn.disabled = false;
      els.input.focus();
    }
  }

  function autoGrow() {
    els.input.style.height = "auto";
    els.input.style.height = Math.min(els.input.scrollHeight, 140) + "px";
  }

  els.input.addEventListener("input", autoGrow);
  els.input.addEventListener("keydown", (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      const text = els.input.value.trim();
      if (text) {
        els.input.value = "";
        autoGrow();
        sendMessage(text);
      }
    }
  });

  els.sendBtn.addEventListener("click", () => {
    const text = els.input.value.trim();
    if (text) {
      els.input.value = "";
      autoGrow();
      sendMessage(text);
    }
  });

  els.resetBtn.addEventListener("click", () => {
    if (confirm("Clear this conversation?")) {
      clearSession();
    }
  });

  function beginChat() {
    els.setup.style.display = "none";
    els.chatWrap.style.display = "block";
    els.composer.style.display = "flex";

    if (messages.length === 0) {
      // Kick off the interview with an opening assistant turn.
      const opener =
        "Hi — I'd like to document a new data processing activity for the Data Mapping Register. Please start the interview.";
      messages.push({ role: "user", content: opener });
      addMessageToDom("user", opener);
      addTypingIndicator();
      callAssistant(messages)
        .then((replyText) => {
          removeTypingIndicator();
          messages.push({ role: "assistant", content: replyText });
          addMessageToDom("assistant", replyText);
          saveSessionState();
          const row = extractJsonBlock(replyText);
          if (row) showResultBar(row);
        })
        .catch((err) => {
          removeTypingIndicator();
          showError(err.message || String(err));
        });
    } else {
      // Re-render restored conversation.
      for (const m of messages) {
        addMessageToDom(m.role, m.content);
        const row = extractJsonBlock(m.content);
        if (row) latestRow = row;
      }
      if (latestRow) showResultBar(latestRow);
    }
    els.input.focus();
  }

  els.startBtn.addEventListener("click", beginChat);

  // Restore any in-progress session for this tab.
  restoreSessionState();
})();
