(function () {
  "use strict";

  const ANTHROPIC_URL = "https://api.anthropic.com/v1/messages";
  const ANTHROPIC_VERSION = "2023-06-01";

  const els = {
    setup: document.getElementById("setup"),
    apiKeyInput: document.getElementById("api-key"),
    modelSelect: document.getElementById("model"),
    startBtn: document.getElementById("start-btn"),
    chatWrap: document.getElementById("chat-wrap"),
    composer: document.getElementById("composer"),
    input: document.getElementById("input"),
    sendBtn: document.getElementById("send-btn"),
    resultBar: document.getElementById("result-bar"),
    dlCsv: document.getElementById("dl-csv"),
    dlJson: document.getElementById("dl-json"),
    dlMd: document.getElementById("dl-md"),
    resetBtn: document.getElementById("reset-btn"),
  };

  let messages = []; // {role, content}
  let latestRow = null; // parsed JSON object once finalized
  let sending = false;

  function saveSessionState() {
    try {
      sessionStorage.setItem("dm_api_key", els.apiKeyInput.value.trim());
      sessionStorage.setItem("dm_model", els.modelSelect.value);
      sessionStorage.setItem("dm_messages", JSON.stringify(messages));
    } catch (e) {
      /* ignore storage errors (private browsing, etc.) */
    }
  }

  function restoreSessionState() {
    try {
      const key = sessionStorage.getItem("dm_api_key");
      const model = sessionStorage.getItem("dm_model");
      const msgs = sessionStorage.getItem("dm_messages");
      if (key) els.apiKeyInput.value = key;
      if (model) els.modelSelect.value = model;
      if (msgs) {
        messages = JSON.parse(msgs);
      }
    } catch (e) {
      /* ignore */
    }
  }

  function clearSession() {
    try {
      sessionStorage.removeItem("dm_api_key");
      sessionStorage.removeItem("dm_model");
      sessionStorage.removeItem("dm_messages");
    } catch (e) {
      /* ignore */
    }
    location.reload();
  }

  function addMessageToDom(role, text) {
    const wrap = document.createElement("div");
    wrap.className = "msg " + role;
    const bubble = document.createElement("div");
    bubble.className = "bubble";
    bubble.textContent = stripJsonBlock(text);
    wrap.appendChild(bubble);
    els.chatWrap.appendChild(wrap);
    els.chatWrap.scrollTop = els.chatWrap.scrollHeight;
    return bubble;
  }

  function addTypingIndicator() {
    const wrap = document.createElement("div");
    wrap.className = "msg assistant";
    wrap.id = "typing-indicator";
    const bubble = document.createElement("div");
    bubble.className = "bubble";
    bubble.innerHTML = '<span class="typing"><span></span><span></span><span></span></span>';
    wrap.appendChild(bubble);
    els.chatWrap.appendChild(wrap);
    els.chatWrap.scrollTop = els.chatWrap.scrollHeight;
  }

  function removeTypingIndicator() {
    const el = document.getElementById("typing-indicator");
    if (el) el.remove();
  }

  function showError(msg) {
    const box = document.createElement("div");
    box.className = "errbox";
    box.textContent = msg;
    els.chatWrap.appendChild(box);
    els.chatWrap.scrollTop = els.chatWrap.scrollHeight;
  }

  // Extract a fenced ```json ... ``` block from assistant text, if present.
  function extractJsonBlock(text) {
    const match = text.match(/```json\s*([\s\S]*?)```/i);
    if (!match) return null;
    try {
      return JSON.parse(match[1].trim());
    } catch (e) {
      return null;
    }
  }

  function stripJsonBlock(text) {
    return text.replace(/```json\s*[\s\S]*?```/i, "").trim() || text;
  }

  function csvEscape(val) {
    const s = val === undefined || val === null ? "" : String(val);
    if (/[",\n]/.test(s)) {
      return '"' + s.replace(/"/g, '""') + '"';
    }
    return s;
  }

  function downloadText(filename, content, mime) {
    const blob = new Blob([content], { type: mime || "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  function buildCsv(row) {
    const header = COLUMNS.map(csvEscape).join(",");
    const values = COLUMNS.map((c) => csvEscape(row[c])).join(",");
    return header + "\n" + values + "\n";
  }

  function buildMarkdown(row) {
    let out = "# Data Mapping Register — Draft Row\n\n";
    out += "_Generated by the Data Mapping Intake Assistant. Review before sending to Legal/Privacy._\n\n";
    for (const c of COLUMNS) {
      out += `**${c}:** ${row[c] && String(row[c]).trim() !== "" ? row[c] : "N/A"}\n\n`;
    }
    return out;
  }

  function showResultBar(row) {
    latestRow = row;
    els.resultBar.classList.add("visible");
  }

  els.dlCsv.addEventListener("click", () => {
    if (!latestRow) return;
    downloadText("data-mapping-row.csv", buildCsv(latestRow), "text/csv");
  });
  els.dlJson.addEventListener("click", () => {
    if (!latestRow) return;
    downloadText("data-mapping-row.json", JSON.stringify(latestRow, null, 2), "application/json");
  });
  els.dlMd.addEventListener("click", () => {
    if (!latestRow) return;
    downloadText("data-mapping-row.md", buildMarkdown(latestRow), "text/markdown");
  });

  async function callClaude(apiKey, model, msgs) {
    const res = await fetch(ANTHROPIC_URL, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": ANTHROPIC_VERSION,
        "anthropic-dangerous-direct-browser-access": "true",
      },
      body: JSON.stringify({
        model: model,
        max_tokens: 2048,
        system: SYSTEM_PROMPT,
        messages: msgs.map((m) => ({ role: m.role, content: m.content })),
      }),
    });

    if (!res.ok) {
      let detail = "";
      try {
        const errJson = await res.json();
        detail = errJson && errJson.error && errJson.error.message ? errJson.error.message : JSON.stringify(errJson);
      } catch (e) {
        detail = await res.text();
      }
      throw new Error(`Anthropic API error (${res.status}): ${detail}`);
    }

    const data = await res.json();
    const text = (data.content || [])
      .filter((b) => b.type === "text")
      .map((b) => b.text)
      .join("\n");
    return text;
  }

  async function sendMessage(userText) {
    if (sending) return;
    sending = true;
    els.sendBtn.disabled = true;

    messages.push({ role: "user", content: userText });
    addMessageToDom("user", userText);
    saveSessionState();

    addTypingIndicator();
    try {
      const apiKey = els.apiKeyInput.value.trim();
      const model = els.modelSelect.value;
      const replyText = await callClaude(apiKey, model, messages);
      removeTypingIndicator();

      messages.push({ role: "assistant", content: replyText });
      addMessageToDom("assistant", replyText);
      saveSessionState();

      const row = extractJsonBlock(replyText);
      if (row) showResultBar(row);
    } catch (err) {
      removeTypingIndicator();
      showError(err.message || String(err));
    } finally {
      sending = false;
      els.sendBtn.disabled = false;
      els.input.focus();
    }
  }

  function autoGrow() {
    els.input.style.height = "auto";
    els.input.style.height = Math.min(els.input.scrollHeight, 140) + "px";
  }

  els.input.addEventListener("input", autoGrow);
  els.input.addEventListener("keydown", (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      const text = els.input.value.trim();
      if (text) {
        els.input.value = "";
        autoGrow();
        sendMessage(text);
      }
    }
  });

  els.sendBtn.addEventListener("click", () => {
    const text = els.input.value.trim();
    if (text) {
      els.input.value = "";
      autoGrow();
      sendMessage(text);
    }
  });

  els.resetBtn.addEventListener("click", () => {
    if (confirm("Clear this conversation and your API key from this browser tab?")) {
      clearSession();
    }
  });

  function beginChat() {
    const apiKey = els.apiKeyInput.value.trim();
    if (!apiKey) {
      alert("Please enter your Anthropic API key to continue.");
      return;
    }
    saveSessionState();
    els.setup.style.display = "none";
    els.chatWrap.style.display = "block";
    els.composer.style.display = "flex";

    if (messages.length === 0) {
      // Kick off the interview with an opening assistant turn.
      messages.push({
        role: "user",
        content:
          "Hi — I'd like to document a new data processing activity for the Data Mapping Register. Please start the interview.",
      });
      addMessageToDom("user", "Hi — I'd like to document a new data processing activity for the Data Mapping Register. Please start the interview.");
      addTypingIndicator();
      const apiKeyVal = apiKey;
      const model = els.modelSelect.value;
      callClaude(apiKeyVal, model, messages)
        .then((replyText) => {
          removeTypingIndicator();
          messages.push({ role: "assistant", content: replyText });
          addMessageToDom("assistant", replyText);
          saveSessionState();
          const row = extractJsonBlock(replyText);
          if (row) showResultBar(row);
        })
        .catch((err) => {
          removeTypingIndicator();
          showError(err.message || String(err));
        });
    } else {
      // Re-render restored conversation.
      for (const m of messages) {
        addMessageToDom(m.role, m.content);
        const row = extractJsonBlock(m.content);
        if (row) latestRow = row;
      }
      if (latestRow) showResultBar(latestRow);
    }
    els.input.focus();
  }

  els.startBtn.addEventListener("click", beginChat);

  // Restore any in-progress session for this tab.
  restoreSessionState();
})();
